# Generated by Django 2.2.4 on 2020-12-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessBlog', '0002_auto_20201221_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='post_author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_title',
        ),
    ]
